### PR TITLE
Rework the CameraView to use multiple views that flow together

### LINKED ISSUE #124: Break up camera view class into smaller components

### PR DESCRIPTION
**Pull request by hjarrell**
Reworks the view so that the monolith CameraView is split into a flow of different views. This cleans up the code and makes it easier to develop.

Closes #124

### CODE REVIEW

**Comment by hjarrell** [comment]
Need to double check but this should close #108

**Comment by hjarrell** [comment]
Also closes #100

**Review by DavidSadowsky — CHANGES_REQUESTED** [review]
I am able to discard the video while the loading screen is displayed - this breaks the app so the submit button no longer works
IMG_5177

The 'X' icon should be in the top left corner instead of top right
IMG_5180

Playback control alignment is off and it doesn't disappear during countdown or recording
IMG_5182

There's also a bug where if you try to reupload a new video, your recorded video won't save and you won't be moved to the next step.
Error message: Could not save video Optional(Error Domain=PHPhotosErrorDomain Code=-1 "(null)"))

**Comment by hjarrell** [comment]
I think I fixed all the issues discovered. Please verify that the reupload issue is fixed because I couldn't recreate it.

**Review by DavidSadowsky — APPROVED** [review]
Looks great 👍

**Pull request merged**
